### ISSUE TITLE
Feature proposition : use existing shared folders and groups created with GroupFolders in Workplace

### ISSUE THREAD

**Issue by stanlog** [arawa/workspace#853]
I use GroupFolders in Nextcloud for a while. I looked for the use of official GroupFolders module version in Workplace before install it. Yesterday I installed and started to use it.

I don't know if I forgot something, but in can't list already created folders with GroupFolders before. I need to recreate all shared repositories :( Do you confirm ?

Another thing, I can't use existing groups in Workplace. I have to create one new group for each workplace if I want to use groups rather than users. In my use of GroupFolders, I don't have one group per folder, I can need to use different groups on a folder, for example "office team" can access to folders named "office", "accounting", "exploitation", ...

Have you planned to manage this kind of use in a future version ?
Thank you so much for this app, really cool work anyway :)

**Comment by dorianne-arawa** [comment]
Hi @stanlog, 

Thank you for your questions. 
In fact, Workspace are Group folders, but Group folders are not Workspaces. Even if you already have group folders on your instance, it won't appear in Workspace. But when you look at the Group folder management interface you will see both. Worksapce works this way for the moment. 

Also, for the moment you can't use existing groups in Workspace app. It's a new feature we are working on. The Workspace app was initialy created for Nextcloud instance without LDAP/AD groups of users, that's why we added the possibility to create groups of users inside Workspace. 

Workspace is an add to Groupfolders and maybe your needs are totaly fullfilled by the group folders app.  Workspace is interesting in terms of delegation (Workspace Manager and General Manager roles), and for the possibility for a non admin user (WM or GM) to create local groups of users in nextcloud, linked to a Workspace. 

I hope my answers will help you to understand the goal of the application. Don't hesitate to ask some other questions :)

Best,
Dorianne from Arawa

**Comment by zak39** [comment]
Hi everyone :)

I think this issue is resolved.

I close this issue, but you can continue to comment.
